defaults:
  - _self_
  - data: pusht

output_model_name: lewm
subdir: ${hydra:job.id}

num_workers: 6
train_split: 0.9
seed: 3072
img_size: 224
patch_size: 14
encoder_scale: tiny
dump_object: True

trainer:
  devices: auto
  accelerator: gpu
  precision: bf16
  gradient_clip_val: 1.0

loader:
  batch_size: 128
  num_workers: ${num_workers}
  persistent_workers: True
  prefetch_factor: 3
  pin_memory: True

optimizer:
  type: AdamW
  lr: 1e-5
  weight_decay: 1e-3
  max_epochs: 100
 

wandb:
  enabled: True
  config:
    entity: montone-guglielmo-wb
    project: lewm
    name: ${output_model_name}
    id: ${subdir}
    resume: allow
    log_model: False

wm:
  type: lewm
  history_size: 3
  num_preds: 1
  embed_dim: 192

encoders:
  vision_encoder:
    num_conv_layers: 2
  proprio_encoder:
    hidden_dim: 100
    embed_dim: 100
  state_encoder:
    hidden_dim: 100

decoder:
  action_decoder:
    embed_dim: 10
    hidden_dim: 100

predictor:
  hidden_dim: 64
  num_steps: 100
  num_layers: 4

loss:
  sigreg:
    weight: 0.09
    kwargs:
      knots: 17
      num_proj: 1024
